# dev namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# hello world deployment in the dev namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest
        ports:
        - containerPort: 80
---
# production namespace
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
# hello world deployment in the production namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest
        ports:
        - containerPort: 80
---
# Alpha namespace
apiVersion: v1
kind: Namespace
metadata:
  name: alpha
---
# hello world deployment in the Alpha namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest
        ports:
        - containerPort: 80